; bed.g
; called to level the bed
;
; generated by RepRapFirmware Configuration Tool v3.6.5 on Sat Nov 22 2025 19:52:59 GMT-0800 (Pacific Standard Time)

M561 ; clear any bed transform
G29 ; call mesh bed compensation
